
services:
  sqlite3:
    # hmm... runs, but not access; SQLAlchemy syntax for sqlite service?  (it's just files below)
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ../../database/:/root/db/
    # thanks: https://stackoverflow.com/questions/65811608/how-to-connect-flask-app-to-sqlite-db-running-in-docker

  mycircles_server:
      image: tylerm007/mycircles
      environment:
        - APILOGICPROJECT_VERBOSE=true
        - SECURITY_ENABLED=true
        ## todid - use default database uri's:
        - APILOGICPROJECT_SQLALCHEMY_DATABASE_URI=sqlite:////my/sqlite/path/mycircles.sqlite
        - APILOGICPROJECT_SQLALCHEMY_DATABASE_URI_AUTHENTICATION=sqlite:////my/sqlite/path/authentication_db.sqlite
      expose:
        - 5656
      ports:
        - 5656:5656
      volumes:
        # local:path-in-container
        - ../:/card-deck-manager
        - ../../database/:/my/sqlite/path/

  mycircles_frontend:
    image: tylerm007/card-deck-manager
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:5656/api
      - 5173:5173
    volumes:
      - ../:/card-deck-manager
    depends_on:
      - mycircles_server
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./landing_page.html:/usr/share/nginx/html/landing_page.html:ro
    depends_on:
      - mycircles_server
      - mycircles_frontend