# cd devops/keycloak; docker compose -f docker-compose-dev-network.yml up

# network: https://stackoverflow.com/questions/44073387/is-it-possible-to-expose-http-ports-with-docker-compose
services:
  mycircles:
    image: tylerm007/mycircles
    environment:
      - APILOGICPROJECT_VERBOSE=true
      - SECURITY_ENABLED=true
      # Set KEYCLOAK_BASE to the internal Docker network hostname and port
      - KEYCLOAK_BASE=http://localhost
      # Set KEYCLOAK_BASE_URL to the realm endpoint (adjust 'kcals' to your realm name)
      - KEYCLOAK_BASE_URL=http://localhost/realms/kcals
      - APILOGICPROJECT_SQLALCHEMY_DATABASE_URI=postgresql://postgres:p@postgresql-service/circles
      - APILOGICPROJECT_SQLALCHEMY_DATABASE_URI_AUTHENTICATION=postgresql://postgres:p@postgresql-service/authdb
    expose:
      - 5656
      - 5173
    ports:
      - 5656:5656
      - 5173:5173

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    restart: always
    #command: start --hostname-strict=false --proxy edge --hostname-url https://kc.hardened.be --hostname-strict-https=false
    command: start-dev --import-realm --proxy=edge --hostname-strict=false --hostname-strict-https=false
    ports:
        - 8080:8080
    volumes:
        - $PWD/import:/opt/keycloak/data/import
    environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=password

  nginx:
    image: nginx:latest
    depends_on: 
        - keycloak
    container_name: nginx
    volumes:
        - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
        - $PWD/nginx/cert.pem:/root/cert.pem
        - $PWD/nginx/key.pem:/root/key.pem
        - $PWD/nginx/admin-app:/usr/share/nginx/html/admin-app
    ports:
        - 80:80
        - 443:443
  
