version: '3'

# cd devops/keycloak; docker compose -f docker-compose-dev-network.yml up

# network: https://stackoverflow.com/questions/44073387/is-it-possible-to-expose-http-ports-with-docker-compose

services:

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    restart: always
    #command: start --hostname-strict=false --proxy edge --hostname-url https://kc.hardened.be --hostname-strict-https=false
    # use next for import, or next+1 for data
    command: start-dev --import-realm --proxy=edge --hostname-strict=false --hostname-strict-https=false
    # command: start-dev  --proxy=edge --hostname-strict=false --hostname-strict-https=false
    ports:
        - 8080:8080
    volumes:
        # - $PWD/devops/keycloak/import:/opt/keycloak/data/import
        # use next for import, or next+1 for data
        - $PWD/import:/opt/keycloak/data/import
        # - $PWD/data:/opt/keycloak/data
    environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=password
    services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=localhost
      - KC_PROXY=edge
      - KC_HTTP_ENABLED=true
      - KC_EMAIL_FROM=tyler.band@aimicroservice.com
      - KC_EMAIL_HOST=smtp.gmail.com
      - KC_EMAIL_PORT=587
      - KC_EMAIL_USER=tyler.band@aimicroservice.com
      - KC_EMAIL_PASSWORD=your-smtp-password
      - KC_EMAIL_STARTTLS=true
  

networks:
  network1:
    name: dev-network
    external: true