# docker build -f Dockerfile -t tylerm007/ontimizeweb --rm .
# docker push tylerm007/ontimizeweb:latest
# cd <project>  
# sh ./ui/app/docker compose -f docker-compose-ontimize.yml up -d
# --> builds, runs at localhost/ontimize, and logs to console
services:
    ontimizeweb:
        image: tylerm007/ontimizeweb
        container_name: ontimizeweb
        expose:
          - 4300
        ports:
          - 4300:4300
        volumes:
          # local:path-in-container
          #- ../ui/app/nginx:/etc/nginx  
          - ../app/dist:/usr/share/nginx/html
        environment:
          - NODE_ENV=production
